import os

configfile: "config.yml"

def get_populations():
    populations = {}
    with open(config['populations_file']) as f:
        for line in f:
            line = line.strip().split()
            populations[line[0]] = line[1:]
    
    return populations

def get_chromosomes():
    chromosomes = []
    with open(config["chromosome_file"], 'r') as f:
        for line in f:
            line = line.strip()
            chromosomes.append(line)

    return chromosomes

rule population_chromosome_vcf:
    input:
        config['vcf_file']
    output:
        "results/vcf/{chromosome}/{population}.vcf.gz"
    run:
        individuals = ','.join(get_populations[wildcards.population])
        shell(f"bcftools view -s {individuals} -r {wildcards.chromosome} -Oz -o {output} {input}")

rule scan_hh_ihs:
    input:
        "results/vcf/{chromosome}/{population}.vcf.gz"
    output:
        "results/ihh/{chromosome}/{population}.Rdata",
        "results/ihs/{chromosome}/{population}.csv"
    script:
        "scripts/scan_hh_ihs.R"

rule xpehh:
    input:
        "results/ihh/{chromosome}/{pop1}.Rdata",
        "results/ihh/{chromosome}/{pop2}.Rdata"
    output:
        "results/xpehh/{chromosome}/{pop1}-{pop2}.csv"
    script:
        "scripts/xpehh.R"
